services:
  db:
    image: postgres:16
    container_name: matriz-curricular-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./sql:/docker-entrypoint-initdb.d/sql
    environment:
      POSTGRES_DB: matrizcurricular
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d matrizcurricular" ]
      interval: 3s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: matriz-curricular-keycloak
    command: start-dev --import-realm
    volumes:
      - ./keycloak-config/matriz-realm.json:/opt/keycloak/data/import/realm.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_DB: postgres
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 5s
    depends_on:
      - db
    ports:
      - "8080:8080"

  backend:
    image: docker0599/matriz-curricular-backend:latest
    container_name: matriz-curricular-backend
    environment:
      - DB_URL=jdbc:postgresql://db:5432/matrizcurricular
      - KEYCLOAK_BACKEND_SECRET=${KEYCLOAK_BACKEND_SECRET}
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    ports:
      - "8081:8080"

  frontend:
    image: docker0599/matriz-curricular-frontend:latest
    container_name: matriz-curricular-frontend
    ports:
      - "80:80"
    restart: always

volumes:
  postgres_data: